POST https://localhost:8080/demo/ad

###
GET https://localhost:8080/demo/al


###
GET https://localhost:8080/demo/up


###
GET https://localhost:8080/demo/gbl

###
GET https://localhost:8080/demo/userlog

###
GET https://localhost:8080/demo/del

###
GET https://localhost:8080/demo/img